spring:
    profiles: dev
    application:
        name: config-client

server:
    port:1301
    
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:2002/eureka/

info:
    des: 这是devdevdevdev
    author: x2yu