
---

server:
    port: 1301
    
spring:
    profiles: sit
    application:
        name: config-client
    
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:2002/eureka/

info:
    des: 这是doc1的sit配置文件
    author: x2yu